# Generated by Django 2.2.7 on 2019-11-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biograpjy',
            new_name='bio',
        ),
    ]
